name: Build and Automate NetToggle Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java Development Kit (JDK)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup GitHub Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.7'

    - name: Accept Licenses and Install SDK 36
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-36"

    - name: Compile Release APK using Gradle
      run: gradle assembleRelease -PversionCode=${{ github.run_number }} -PversionName=1.0.${{ github.run_number }}

    - name: Decode Permanent Keystore
      run: |
        cat << 'EOF' > encoded_key.txt
        ${{ secrets.KEYSTORE_BASE64 }}
        EOF
        sed -i '/---/d' encoded_key.txt
        tr -d '\r\n ' < encoded_key.txt | base64 --decode > release.keystore

    - name: Zipalign and Sign Release APK (V2 Signature)
      run: |
        BUILD_TOOLS_DIR=$(ls -d $ANDROID_HOME/build-tools/* | tail -1)
        
        $BUILD_TOOLS_DIR/zipalign -v -p 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-aligned.apk
        
        $BUILD_TOOLS_DIR/apksigner sign --ks release.keystore --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} --out app/build/outputs/apk/release/NetToggle.apk app/build/outputs/apk/release/app-release-aligned.apk

    - name: Upload APK as Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NetToggle-Package
        path: app/build/outputs/apk/release/NetToggle.apk
        compression-level: 0
